# Generated by Django 5.2 on 2025-04-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency_app', '0002_alter_user_role_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_church', models.CharField(max_length=255)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_residents', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residency_app.cohort')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'resient'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
