# Generated by Django 5.2 on 2025-04-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency_app', '0003_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='resident',
            field=models.ManyToManyField(blank=True, related_name='assigned_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='coordinator',
            field=models.ForeignKey(limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('coordinator', 'Coordinator'), ('coach', 'Coach'), ('resident', 'Resident')], max_length=20),
        ),
    ]
